import pandas as pd
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])
print("Series 1:\n", s1)
print("Series 2:\n", s2)
# Vertical stacking (one below another)
vertical = pd.concat([s1, s2])
print("\nVertical stacking:\n", vertical)
# Horizontal stacking (side by side)
horizontal = pd.concat([s1, s2], axis=1)
print("\nHorizontal stacking:\n", horizontal)
